version: '3.8'

# Define the services/ containers to be run
services:
   # angular: # name of the first service
   #    build: angular-app # specify the directory of the Dockerfile
   #    volumes:
   #       - ./angular-app:/app # this will enable changes made to the angular app reflect in the container

   express: # name of the second service
      build: backend # specify the directory of the Dockerfile
      ports:
         - '3000:3000' #specify ports mapping
      depends_on:
         - database # link this service to the database service

   database: # name of the third service
      image: mongo # specify image to build container from
      ports:
         - '27017:27017' # specify port forwarding
